In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
a[0]

1

In [5]:
size = 100000


2

In [6]:
import time
import sys

NameError: ignored

In [8]:
print(sys.getsizeof(5)*len(b))

28000


In [13]:
a = np.array([[4,5,6],[6,7,8]])
print(a)

[[4 5 6]
 [6 7 8]]


In [14]:
a.ndim


2

In [15]:
a.itemsize

8

In [16]:
a.shape

(2, 3)

In [22]:
a = np.array([[1.0,2.0],[3.0,4.0],[5.0,6.0]],dtype = float)

In [23]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [24]:
 a.itemsize

8

In [25]:
print(np.char.upper(["Hello How are you","How is this going"]))

['HELLO HOW ARE YOU' 'HOW IS THIS GOING']


In [28]:
print(np.split(["are, you ,coming ,to, the, partly"]))

TypeError: ignored

In [29]:
print(np.char.splitlines('hellow how are you'))

['hellow how are you']
